### ISSUE TITLE
Support for AllowUnknownFlags

### ISSUE THREAD

**Issue by simongottschlag** [cristalhq/aconfig#105]
Hi!

I've been using aconfig for a while now and I love it! Thank you for all the hard work. 😊👍

I'm trying to load the same flags using different structs in two places in my program and it always complains about the flag not being defined. I've tried using `AllowUnknownFlags` without success.

The gist of it is I create a struct with the field `A` and load it during the initialization of the program, then later on I load a struct with the field `B`. I then start the program like this: `go run main.go --a foo --b bar`

When loading the first struct with only `A`, it says `-b is not defined`.

Any ideas? I'm on the phone now, but can paste a test I built to debug tomorrow if you'd like.

Thank you again!

**Comment by cristaloleg** [comment]
Hi @simongottschlag thank you for the kind words and sorry for the troubles. Looks like the problem is realted to the behaviour of the stdlib flag package.


Im pn vacation till Sunday without laptop, will be not able to fix sooner :( will attack this problem on Sunday, ok?

**Comment by simongottschlag** [comment]
Hi @cristaloleg!

I'm in no hurry, this case is for an example for a pet project. 😊

If I get the time during the week, I'll dig into the problem a bit deeper and see if I can create a PR for you to review next week.

Have a great vacation! 🎉
