### ISSUE TITLE
yaml decorder can't open file in embed file system

### ISSUE THREAD

**Issue by MockyBang** [cristalhq/aconfig#125]
in the aconfigyaml package, [DecodeFile](https://github.com/cristalhq/aconfig/blob/e7fea81176121954eef8326a9c1e14a0cb5f9525/aconfigyaml/yaml.go#L21) func use os.Open to open file, when in embed file system, it can't find file then throw an err: "no such file or directory"。
but when using default json decorder, [jsonDecoder](https://github.com/cristalhq/aconfig/blob/e7fea81176121954eef8326a9c1e14a0cb5f9525/utils.go#L153) has a fsys field, which can open file in embed file system.

hope you can fix this bug in aconfigyaml package.

**Comment by cristaloleg** [comment]
Hi @MockyBang sorry for the troubles. Yes, I did a mistake not adding support for FS in aconfigyaml(and other packages). Will take care of it. Thanks for reporting!

**Comment by cristaloleg** [comment]
Have released all decoders as v0.17.1. Do `go get github.com/cristalhq/aconfig/aconfigyaml@v0.17.1` to get new version.
