### ISSUE TITLE
Override flag and env

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [cristalhq/aconfig#3]
## Problem

Having such a config
```
type MyConfig struct {
	Port int
	MyAuth MyAuth `yaml:"myAuth"`
}

type MyAuth struct {
	MyUser string `yaml:"myUser" default:"def-user"`
}
```
I can parametrize it with
```
APP_MYAUTH_MYUSER=jakub
--myauth.myuser jakub
```

What I would like to do is to handle CamelCase config properly. In such cases I'd rather have something like this:
```
APP_MY_AUTH_MY_USER=jakub
--my-auth-my-user=jakub
```

In other words, I'd like to override default env and flag.

Note: With yaml I had to put `myauth.myuser`, but `yaml` tag is taken into account.

## Proposal

How about introducing new tag
```
type MyConfig struct {
	Port int
	MyAuth MyAuth `yaml:"myAuth"`
}

type MyAuth struct {
	MyUser string `yaml:"myUser" env:"my_auth_my_user" flag:"my-auth-my-user" default:"def-user"`
}
```

`env` could also be hierarchical like this:
```
type MyConfig struct {
	Port int
	MyAuth MyAuth `yaml:"myAuth" env:"my_auth"`
}

type MyAuth struct {
	MyUser string `yaml:"myUser" env:"my_user" default:"def-user"`
}
```
But I've got bad experience with it from envconfig. because you then don't know if you need parse `app_myauth_my_user` or just `app_my_user` if `env:"my_auth"` is missing.

**Comment by cristaloleg** [comment]
Sounds reasonable. I was waiting for this(or similar) issue to be able to configure field's env name :)

For me configuring name per field is more natural, 'cause this matches with JSON/YAML/TOML behaviour. 

According to title changing flag name should be done too.
