### ISSUE TITLE
Description of configs

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [cristalhq/aconfig#4]
## Problem

Having an option to generate default flags is really nice! but it's not that useful if I cannot write help for this. So for example:
```
❯❯❯ ./samplego --help
Usage:
  -myauth.lease string
    	 (default "3s")
  -myauth.multiple string

  -myauth.mypass string
    	 (default "def-pass")
  -myauth.myuser string
    	 (default "def-user")
  -port string
```
I want to communicate to a user what are those properties.

## Proposal

Ideally, I'd like to put a comment like this
```
type MyAuth struct {
	// user that will use the server
	MyUser string `yaml:"myUser" default:"def-user"`
}
```
but I don't think it's technically possible to then use it in the code (unless some generator that will parse it?)

so the other option would be to introduce a tag for it.
```
type MyAuth struct {
	MyUser string `yaml:"myUser" default:"def-user" description:"user that will user server"`
}
```
This way I could even reuse it and autogenerate generate configuration for yaml and envvars

**Comment by cristaloleg** [comment]
Yep, one more expected issue feature :D 

Completely agree, I also was looking for comment as a doc solution, but it's not possible without full code parsing (also imagine, when config consists of different structs from different packages or even modules). Even with an explicit `go:generate` it will be plenty of thing to do which is probably out of scope for this lib.

But! there is already a constant (https://github.com/cristalhq/aconfig/blob/master/aconfig.go#L20) which is planed to be used as a field description. Treat it as work in progress.

I haven't implemented it yet, 'cause was looking for a solution when user can generate it's own documentation for the config. Maybe:
```
loader.WalkFields(func(f *aconfig.Field) {
	_ = f.Name() // also env, flag names
	_ = f.DefaultValue()
	_ = f.Usage()
	_ = f.Parent() // probably of `aconfig.Field` type
	// and now user can pass this values to some kind of template and generate whatever it's possible
})
```

Probably it's ok to start with a simple one (add `usage` or `description` tag) and wait for a feedback.

**Comment by jakubdyszkiewicz** [comment]
Awesome, `usage` works like expected!

`loader.WalkFields` looks pretty good. I'd like to also extract `yaml` tag and I see that TOML uses `toml` tag, so maybe add `f.Tag(String)` to `aconfig.Field`?

**Comment by cristaloleg** [comment]
Agree, limiting to `aconfig`-known tags is strange, common `f.Tag(string) string` methods will be much better.
