### ISSUE TITLE
Add Cobra example

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [cristalhq/aconfig#6]
Cobra seems to be a default way to do CLI in Go. The first thing I checked is whether I can integrate it with Cobra while adding some other flags outside of the config.

It turned out it works really well! 

```
type MyConfig struct {
	Port int
}

func main() {
	loader := aconfig.LoaderFor(&MyConfig{}).
		WithEnvPrefix("app").
		WithFiles([]string{"ouch.yaml"}).
		Build()
	args := struct {
		logLevel string
	}{}
	cmd := &cobra.Command{
		Use:   "hello",
		RunE: func(cmd *cobra.Command, _ []string) error {
			var cfg MyConfig
			if err := loader.Load(&cfg); err != nil {
				return err
			}

			cmd.Printf("Hello World!")
			return nil
		},
	}
	cmd.PersistentFlags().AddGoFlagSet(loader.Flags())
	cmd.PersistentFlags().StringVar(&args.logLevel, "log-level", "info", "log level: debug, info, warning")

	if err := cmd.Execute(); err != nil {
		os.Exit(1)
	}
}
```

I would create a PR, but I'm not sure how (or if 😄) would you like to add it, I don't want to put Cobra in `go.mod` and this example might be too big for `README.md`.

**Comment by cristaloleg** [comment]
Well, you can write a short blogpost(even tweet) with this example and I'll happily add it :D

From the other side: adding this example in README as a Go Playground URL seems reasonable, feel free to make a PR 👌
