### ISSUE TITLE
Configurable slice separator from env

### ISSUE THREAD

**Issue by s3rj1k** [cristalhq/aconfig#63]

**Comment by cristaloleg** [comment]
Looks like `,` isn't working for you, can you show me a full case? thanks.

**Comment by s3rj1k** [comment]
@cristaloleg Use case: golang application starts another one (exec) and commandPath, commandArgs are passed to original application via envs.

So there is env variable that contains args for cmd.exec as string, but this is inconviniat as application needs to do strings.Fileds() on this variable to split args (by spaces) and pass slice to cmd.

Thanks.

**Comment by cristaloleg** [comment]
So why not to call `strings.Split(someSliceFromEnv, ",")` and pass this to a second app? or I get you wrongly?

**Comment by s3rj1k** [comment]
@cristaloleg some abstract example with envs setup, I want to run `ls -l -a -h`
```
CMD_COMMAND="/usr/bin/ls"
CMD_ARGS="-l -a -h"
```

Reading envs to config struct:
```
type Config struct {
  Command string
  Args []string
}
```

I get `c.Args = []string{"-l -a -h"}` and I would like to get `c.Args = []string{"-l", "-a", "-h"}` instead :)

Of course I can use  `Args string` instead of `Args []string` and split this manually, but aconfig already has support for slices and splits them by separator, so adding customizable separator is an obvious solution.

**Comment by cristaloleg** [comment]
I've some doubts that after adding slice separator for env there will be a request to add same for flags, then both for list of key-values and then for key-values.

IMO, currently loader's config is big enough and the simplest solution will be to change param type to string and treat at as 'raw' params.

(there is a #47 which addresses issues with slices and maps(support of them is hacky now), but currently it's a WIP)

**Comment by s3rj1k** [comment]
@cristaloleg Doesn't really matter if data comes from flags or from env.

You could potentially have slice elements that have `,` how do you propose to get around this with current slice implementation?

**Comment by cristaloleg** [comment]
For this case - doesn't matter, but I'm rushing to add param for this and than all other mentioned above. 

Yep, there is no solution. I would like to hear more real-life examples and see what fits better. Adding feature with separator param and the removing it is not cool, that's why I would like to postpone it a bit.

So the shortest and simplest solution for your case - make manual split and pass params. We will see what future will give us.

**Comment by s3rj1k** [comment]
@cristaloleg You can checkout other similar projects, they all allow to customize slice separator if they support slices in config structures. Sadly they all also lack some other features (mainly related to what they have currently implemented) in them :)

IMO: Doing some custom logic with config structs after parsing input data by `aconfig` defies main principal of such a library, i.e. handling configuration internally without worrying about this in main application code.

**Comment by cristaloleg** [comment]
Currently I see `strings.Split` as a simpler solution for this. Happy to revisit this feature later.

**Comment by s3rj1k** [comment]
@cristaloleg So what is the point for `aconfig` in the first place?)

One can manually parse to structs all envars .)

Feel free to close with `WONTFIX`

**Comment by cristaloleg** [comment]
For you - who knows?

If you can then I'm pretty happy about your skills.

Maybe later.

**Comment by cristaloleg** [comment]
Closing as no other users have mentioned their opinion. Feel free to re-open.
