### ISSUE TITLE
Config loading doesn't work for struct pointers

### ISSUE THREAD

**Issue by aovlllo** [cristalhq/aconfig#64]
This small example will fail with error `cannot load config: type kind "struct" isn't supported`:

``` go
type s1 struct {
	A *s2
}

type s2 struct {
        B string
}

var cfg s1
loader := aconfig.LoaderFor(&cfg, aconfig.Config{
	Files:           []string{"/var/opt/myapp/config.json", "ouch.yaml"},
	FileDecoders: map[string]aconfig.FileDecoder{
		// from `aconfigyaml` submodule
		// see submodules in repo for more formats
		".yaml": aconfigyaml.New(),
	},
})

flagSet := loader.Flags()

if err := loader.Load(); err != nil {
	panic(err)
}
```

I prepared quick fix and additional test for this case in my fork, but I don't know your ideology for pointers in configs. I guess some note about this limitation should be added to Readme at least If you don't want to fix this behavior

**Comment by cristaloleg** [comment]
Closed in #65
