### ISSUE TITLE
Only pre-set file extensions are supported

### ISSUE THREAD

**Issue by Tasssadar** [cristalhq/aconfig#71]
This does not work:

```go
aconfig.LoaderFor(dest, aconfig.Config{
	Files:            files,
	FileDecoders: map[string]aconfig.FileDecoder{
		".yaml": aconfigyaml.New(),
		".yml":  aconfigyaml.New(),
	},
})
```

`.yml` files cannot be loaded and fail with `cannot load config: unknown field in file` error, because the struct tags are only [auto-generated for the pre-set formats](https://github.com/cristalhq/aconfig/blob/main/reflection.go#L69-L71). The file format is then recognized via `filepath.Ext`, which is `yml` and not `yaml`.

IMHO the "format" should be returned by the file decoder, maybe as another interface method. I can try to prepare a PR if you'd like to go that way.

EDIT: example of how it might look like without breaking backwards compatibility: https://github.com/avast/aconfig/commit/fbab7665e54111e1cc90a431de747afdbcf7bbff

**Comment by cristaloleg** [comment]
Nice. I thought about that long time ago and haven't found usage of `yml` in my projects or in projects of my friends, so I leave it.

Also I thought about a simpler fix, just add an `yml` entry when `yaml` is detected. I know, it sounds like a hack, but how many file formats make sense to support? :)

+ such solution (even hacky, but no horrible) will not add new dependencies, just an if. WDYT ?

(sorry for a delay, was on vacation)

**Comment by cristaloleg** [comment]
See #74. Only 2 `if`s :)

**Comment by Tasssadar** [comment]
Yeah, that does fix my use case completely, thanks. I'm also for adding more documentation to `FileDecoders` config option - it makes it look like any arbitrary extension or even decoder is supported, when this is in fact not the case.

**Comment by cristaloleg** [comment]
Good point. I will merge #74 now. Regarding `FileDecoders` and it's behaviour - would like to make it more reasonable, maybe there must be extension + format or as you've proposed decoder knows what it supports. Not sure at all.
