### ISSUE TITLE
FileDecoders is limited only to standard extensions

### ISSUE THREAD

**Issue by asv7c2** [cristalhq/aconfig#78]
If register non standard extension for file decoder - than it cannot found any field during load. Is this by design?

**Comment by cristaloleg** [comment]
Hi, yep, currently JSON, YAML, TOML and dotenv are supported. So any decoder of this type will work. Which extension is not supported in your case?

**Comment by asv7c2** [comment]
@cristaloleg 
Hi. If i register such extension (can be any other extension):
```
Files:              []string{".config"},
FileDecoders: map[string]aconfig.FileDecoder{
		".config": aconfigyaml.New(),
	},
```
then during load fields cannot be found. I can create repo for issue if need.

**Comment by cristaloleg** [comment]
Yep, currently it will match `.config` extension to `config` structure tag which doesn't exist.

Similar question appeared here https://github.com/cristalhq/aconfig/issues/71#issuecomment-843151517 and I'm not sure how to change API and waiting for the inspiration.

There was an idea:
```go
FileDecoders: []aconfig.Decoders{
	{
		Format: "yaml",
		Extensions: ".yaml",
		Decoder: aconfigyaml.New(),
	},
	{
		Format: "yaml",
		Extensions: ".config",
		Decoder: aconfigyaml.New(),
	},
	{
		Format: "yoyoml",
		Extensions: "yo",
		Decoder: yoyoml.New(),
	},
}
```

CC: @Tasssadar

**Comment by asv7c2** [comment]
@cristaloleg 

Why not add format to interface?
```
// FileDecoder is used to read config from files. See aconfig submodules.
type FileDecoder interface {
  DecodeFile(filename string) (map[string]interface{}, error)
  Format() string
}
```

**Comment by cristaloleg** [comment]
After a 2nd round of this idea I agree, it's better than mine (sorry @Tasssadar :( ). Will add today-tomorrow or feel free to click a PR.
