### ISSUE TITLE
Затруднение при запуске тестов из-под VSCode

### ISSUE THREAD

**Issue by Rid-lin** [cristalhq/aconfig#82]
Добрый день. Очень нравиться этот пакет, но возникли сложности.
При попытке использовать библиотеку при запуске тестов выходит ошибка о неизвестном(not defined) флаге.
запуск осуществляется через VSCode контекстным пунктом или "run test" или "debug test"
Вывод:
```
Running tool: C:\Go\bin\go.exe test -timeout 30s -run ^TestAliasType_send$ package

flag provided but not defined: -test.testlogfile
Usage:
```
Далее идет вывод использования программы как будто указан неверный флаг или указан "-help"
И возвращается ошибка с текстом:
`flag provided but not defined: -test.testlogfile`
параметр в конфиге `AllowUnknownFlags:  true,` стоит, 
версия `github.com/cristalhq/aconfig v0.14.1`
Я что-то делаю не так?

**Comment by cristaloleg** [comment]
Привет, проблема в том, что `go test` докидывает свои флаги к исполняемым тестам, которые передаются в `aconfig` и парсятся пакетом `flag` из stdlib (`flag provided but not defined` это из `flag.FlagSet`)

Я удивлён, что эта ошибка просочилась до сегодня, просто никто `aconfig` в своих тестах не запускал и не жаловался) Сейчас посмотрю как исправить.

**Comment by cristaloleg** [comment]
2 быстрых фикса:

1. `SkipFlags: true,` если не используешь флаги в тестах
2. Почистить флаги и передать нормальные в `aconfig.Loader`
```go
func TestAliasType_send(t *testing.T) {
	args := []string{}
	for _, a := range os.Args {
		if !strings.HasPrefix(a, "-test.") {
			args = append(args, a)
		}
	}

	loader := aconfig.LoaderFor(dst, aconfig.Config{
		// ...
		Args:     args,
	})
	if err := loader.Load(); err != nil {
		t.Error(err)
	}
	// ...
```

Пока не знаю, как хорошо это исправить, поэтому 2 решения, посмотрю на неделе.

**Comment by Rid-lin** [comment]
Благодарю. Работает. Буду ждать обновлений.

**Comment by cristaloleg** [comment]
Похожу, что `Args: os.Args,` заработает и тогда можно не удалять `-test` ручками

**Comment by cristaloleg** [comment]
Все же `os.Args` не помогает, спасибо @mef13 за дебаг.

Правильный фикс:
```
func TestAliasType_send(t *testing.T) {
	args := []string{}
	for _, a := range os.Args {
		if !strings.HasPrefix(a, "-test.") {
			args = append(args, a)
		}
	}

	loader := aconfig.LoaderFor(dst, aconfig.Config{
		// ...
		Args:     args[1:],  // [1:] важно, см. доку к FlagSet.Parse
	})
	if err := loader.Load(); err != nil {
		t.Error(err)
	}
	// ...
```

Ну или выключить флаги.
