### ISSUE TITLE
Make composite environment variable name optional

### ISSUE THREAD

**Issue by ilyakaznacheev** [cristalhq/aconfig#83]
There are some cases when you can't change the environment variable name to the desired format.

For example, Heroku provides a `PORT` environment variable for you, you can't change the name.

But with the current library implementation, I can't structure my config files like I want to. Example:

```go
type Config struct {
    Server ConfigServer `yaml:"server"`
}

type ConfigServer struct {
    Host string `yaml:"host"`
    Port string `yaml:"port" env:"PORT"`
}
```

The variable name library is looking for will be `SERVER_PORT`, not `PORT`, and I can't change that without restructuring my config structure (and config files!).

Please provide an option to turn off automatically provided env prefixes, to enable exact env names.

**Comment by cristaloleg** [comment]
(discussed on priv)
I will add param to env, so it will looks like: `env:"NAME,exact"` which means that **exact**ly this name will be mapped on to this field.

+ There will be an option to skip name (`env:"-"`) in child fields.
